### ISSUE TITLE
ExifTool for additional file metadata, especially for media?

### ISSUE THREAD

**Issue by RobLewis** [n8gray/Backup-Bouncer#1]
I'm over my head here, but I use the great ExifTool to read and write metadata for media files. Seems like it could perhaps be integrated into Backup-Bouncer to add capabilities. It includes a Perl library as well as a command-line tool.

**Comment by n8gray** [comment]
Hi Rob,

ExifTool is very nice, I agree, but image metadata lives at a different level compared to filesystem metadata, which is what BB tests.  To be slightly technical, _image_ metadata lives inside the file; _filesystem_ metadata does not.  Any time you faithfully copy an image file you'll preserve all _image_ metadata, even if you use a tool that fails every BB _filesystem_ metadata test.

You _do_ need to worry about preserving image metadata when you're loading and saving images in an image editor, but not when you're making backups -- any backup tool will preserve it perfectly.
