### ISSUE TITLE
resource fork tests need ..namedfork under 10.7

### ISSUE THREAD

**Issue by jlillibridge** [n8gray/Backup-Bouncer#2]
Hello,

I've been using your excellent bbouncer to confirm that our Fink version of rsync (3.0.8) is 100% successful in your tests. I just upgraded to 10.7 Lion, and found that the two tests containing resource forks (30 & 99) failed to create the needed test files. I tracked it down to the old 'short form': file/rsrc, no longer being supported in 10.7 (it still was in 10.6 SL).  I modified the two test scripts to use "..namedfork/rsrc" everywhere, and the tests now succeed under Lion. I'd be happy to provide the two patch files, and the copier.d file for Fink rsync, if that would be helpful.

Thanks,
John

**Comment by n8gray** [comment]
Hi John,

Sounds good, go ahead and send the patches or a github pull request
and I'll integrate them.

Thanks for helping out!
-Nathan

On Fri, Aug 12, 2011 at 5:50 AM, jlillibridge
reply@reply.github.com
wrote:

> Hello,
> 
> I've been using your excellent bbouncer to confirm that our Fink version of rsync (3.0.8) is 100% successful in your tests. I just upgraded to 10.7 Lion, and found that the two tests containing resource forks (30 & 99) failed to create the needed test files. I tracked it down to the old 'short form': file/rsrc, no longer being supported in 10.7 (it still was in 10.6 SL).  I modified the two test scripts to use "..namedfork/rsrc" everywhere, and the tests now succeed under Lion. I'd be happy to provide the two patch files, and the copier.d file for Fink rsync, if that would be helpful.
> 
> Thanks,
> John
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/n8gray/Backup-Bouncer/issues/2

## 

HexaLex: A New Angle on Crossword Games for iPhone and iPod Touch
http://hexalex.com
On The App Store: http://bit.ly/8Mj1CU
On Facebook: http://bit.ly/9MIJiV
On Twitter: http://twitter.com/hexalexgame
http://n8gray.org

**Comment by jlillibridge** [comment]
Hi Nathan,

Thanks for the quick reply, and I'm happy to be able to help in just a small way. I don't want to mess things up via github (and only enrolled so I could contact you), so will attach the patches and rsync-fink copier below for you to integrate as you please. It's been very helpful to have bbouncer, and it amazes me that NONE of the Apple copiers are 100% successful. However, rsync (if carefully patched and compiled) passes with flying colors! Thanks to Mike Bombich for making me aware of your very useful utility.

Cheers,
John

**Comment by n8gray** [comment]
Hey John,

Why don't you go ahead and email that patch to me at n8gray /at/ n8gray \dot\ org.

Cheers,
-n8

**Comment by n8gray** [comment]
Hi Andy,

This should be fixed.  I just tried it out on my own Lion machine and
didn't see any problems.  You should verify that you've got the most
recent version (3bd61f60fa4ac0a876f8721f904aac74d6930b56).

Cheers,
-n8

On Sun, Oct 2, 2011 at 11:15 PM, Andy Boutte
reply@reply.github.com
wrote:

> Hi Nathan and John
> 
> I am still getting the error on 30 and 99 using the master branch.  Is there something more I am missing or is still still an ongoing issue?
> 
> Thanks.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/n8gray/Backup-Bouncer/issues/2#issuecomment-2269163

## 

HexaLex: A New Angle on Crossword Games for iPhone and iPod Touch
http://hexalex.com
On The App Store: http://bit.ly/8Mj1CU
On Facebook: http://bit.ly/9MIJiV
On Twitter: http://twitter.com/hexalexgame
http://n8gray.org
